### ISSUE TITLE
Investigate cloud solution to use for services and deployment

### ISSUE THREAD

**Issue by Adzox** [frivara/accounting#2]
Figure out which of the following cloud providers to use for the web service: Google Cloud, Azure, Microsoft Azure and Amazon AWS.

**Comment by Adzox** [comment]
NOTE: we will still write the code in a way so that it can be easily replaceable if needed

**Comment by AlexanderTarler** [comment]
On it!

**Comment by AlexanderTarler** [comment]
After a bit of contemplating/googling/speaking to the spirits of the Internet I have ended up on Firebase as our provider. It's easy to use, the documentation is nice and I have some previous experience using it. The cost, if we were to reach a need for that, is alright, and the free plan gives us a generous amount of space.

**Comment by Adzox** [comment]
Sounds good to me! Will close this issue then!
