### ISSUE TITLE
Decide on React SSR Component library

### ISSUE THREAD

**Issue by Adzox** [frivara/accounting#3]
We want ready-made components for easier and faster creation of the front end.

The following components are needed:

* Table (searchable)
* Collapsible Segments
* Cards
* Buttons
* Icons
* Images
* Text
* Form Inputs

**Comment by AlexanderTarler** [comment]
On it!

**Comment by AlexanderTarler** [comment]
My suggestion is that we go with Material UI. It seems flexible, easy to use and would allow us to create a simple yet enticing UX.

**Comment by Adzox** [comment]
Sounds perfect! Could you add a link and an example screenshot to this issue, before I close it?

**Comment by AlexanderTarler** [comment]
Absolutely! 

https://mui.com/

They have some[ templates](https://mui.com/material-ui/getting-started/templates/) we could check out.

![image](https://github.com/frivara/accounting/assets/113191552/35e8ab59-3f30-4406-b8c2-354c5c7d4fa7)

**Comment by Adzox** [comment]
Perfect! Closing this as done then!
